import { type NextPage } from "next";
import Head from "next/head";
import { signIn, useSession } from "next-auth/react";

import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const { data: sessionData } = useSession();

  useEffect(() => {
    const makeRouter = async () => {
      if (sessionData?.user?.id) {
        await router.replace("/posts");
      }
    };
    makeRouter();
    setLoading(false);
  }, [router, sessionData]);

  if (loading) return null;
  return (
    <>
      <Head>
        <title>Reddit Nextjs Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="body-font flex min-h-screen min-w-full flex-col items-center bg-purple-600 text-white">
        {/* <AuthShowcase /> */}
        <div className="container mx-auto px-5 py-24">
          <div className="mx-auto flex flex-col items-start sm:flex-row sm:items-center lg:w-2/3">
            <h1 className="title-font flex-grow text-2xl font-medium  sm:pr-16">
              Welcome To New Reddit
            </h1>
            <button
              className="rounded-full bg-white/10 px-10 py-3 font-semibold no-underline transition hover:bg-white/20"
              onClick={async () => {
                await signIn();
                router.replace("/posts");
              }}
            >
              Sign In
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

// const AuthShowcase: React.FC = () => {
//   const { data: sessionData } = useSession();

//   const { data: posts } = trpc.posts.getAll.useQuery();

//   return (
//     <div className="flex flex-col items-center justify-center gap-4 text-white">
//       {posts?.map((post) => {
//         return (
//           <div key={post.id}>
//             <h2>Title</h2>
//             <div>{post.title}</div>
//             <h2>Body</h2>
//             <div>{post.body}</div>
//           </div>
//         );
//       })}
//   <button
//     className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//     onClick={sessionData ? () => signOut() : () => signIn()}
//   >
//     {sessionData ? "Sign out" : "Sign in"}
//   </button>
// </div>
//   );
// };
